[build]
  command = "npm run production"
  publish = "public"

[build.environment]
  NODE_VERSION = "14.15.0"
  PHP_VERSION = "8.0"

[build.processing]
  # Exclude unnecessary files from build
  # Adjust this according to your project structure
  exclude = [
    "storage/**",
    "tests/**",
    "vendor/**",
    ".env",
    ".git/**",
    "node_modules/**",
  ]

